version: "2"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/app
    depends_on:
     - postgres
  postgres:
    image: library/postgres
    environment:
      POSTGRES_PASSWORD: "umq"
      POSTGRES_DB: "umq"
    ports:
      - "5432:5432"
