version: "2"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - postgres
    volumes:
      - .:/web
  postgres:
    image: library/postgres
    environment:
      POSTGRES_PASSWORD: "umq"
      POSTGRES_DB: "umq"
    ports:
      - "5432:5432"
