version: "2"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - postgres
    volumes:
      - ./umq:/umq
  postgres:
    image: library/postgres:9.6
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: ""
    ports:
      - "5432:5432"
