services:
  app:
    build:
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
    depends_on:
      - postgres
    env_file: .env

  postgres:
    image: library/postgres:15.4
    environment:
      POSTGRES_PASSWORD: "umq"
      POSTGRES_DB: "umq"
    ports:
      - "5432:5432"