app = "umq"
primary_region = "sea"

[build]
  dockerfile = "Dockerfile.prod"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
